[package]
name = "raicoin"
version = "0.1.0"
authors = ["eadan"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
rust-crypto = "^0.2"
num = "^0.1"
clap = "^2.26"
secp256k1 = "^0.7"
rand = "^0.3"